#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[92m'
NC='\033[0m'
# Helper Functions
error () {
	printf "[${RED}ERROR${NC}] $1\n"
	exit $2
}

warning () {
	printf "[${YELLOW}WARNING${NC}] $1\n"
}

success () {
	printf "[${GREEN}SUCCESS${NC}] $1\n"
}

tick () {
	printf "$1 ${GREEN}✔${NC}\n"
}

# Begin
workdir="$HOME/Documents/noted"
if [ ! -d $workdir ]
then
	mkdir $workdir
fi

if [ ! -f "$workdir/.key" ]
then
	cat << EOF > "$workdir/.key"
nic:<your_nickname>
key:<your_key>
EOF
	error ".key file missing, generating \'$workdir/.key\'... Please fill it out."
fi

while IFS=: read -r key val
do
	if [ $key = 'key' ]
	then
		privkey=$val
	else
		nic=$val
	fi
done < "$workdir/.key"

height=$(ls -1 $workdir | wc -l)
height=$(echo $height + 1 | bc)
file=$(echo -e "NEW\n$(ls -1 $workdir)" | dmenu -l "$height" -p "Files:")
if [ $? -eq 1 ]
then
	exit 0
fi

if [ $file = "NEW" ]
then
	file=$(echo "" | dmenu -p "Enter Filename:")
fi

if [ $? -eq 1 ]
then
	exit 0
fi
file="$workdir/$file"
touch "$file"

height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a task: "

# Loop Credit too https://tools.suckless.org/dmenu/scripts/todo
cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
